--
driver:
  name: vagrant
  
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  
platforms:
  - name: ubuntu-14.04

suites:
  - name: wordpress
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    driver:
      network:
      - [ 'private_network', { ip: '192.168.33.68' } ]
    run_list:
    - recipe[wordpress]
